path: /mnt/ssd1/datasets/open_ai/
predictions-name: predictions_effb4-bs128-steplr-not_filled-nowu.csv
visualize:
  ids: []
prepare-target:
  save: True
make-folds:
  nfolds: 10
  only_verified: True
  verified_in_train: False
inference:
  ids: test_ids.csv
  tta: True
  mode: test
#  clipping: [0.01, 0.99]
evaluation:
  verified_only: True
model:
  folds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  data_params:
    batch_size: 128
    num_workers: 32
    augmentation_params:
      resize: 224
  train_params:
    name: effb4-bs128-steplr-not_filled-nowu
    model: models_zoo.classification.effnet.EffNet
    model_params:
      model_name: efficientnet-b4
      num_classes: 5
    loss: losses.CrossEntropyLoss
    loss_params: {}
    metrics: [losses.CrossEntropyLoss]
    steps_per_epoch: 10000
    accumulation: 1
  stages:
#  -
#    load_best: False
#    optimizer: Adam
#    optimizer_params:
#      lr: 0.00001
#    scheduler: GradualWarmupScheduler
#    scheduler_params:
#      multiplier: 10
#      total_epoch: 10
#    epochs: 10
#    augmentation: mix_transform
  -
    load_best: False
    optimizer: Adam
    optimizer_params:
      lr: 0.0001
    scheduler: MultiStepLR
    scheduler_params:
      milestones: [7, 10]
      gamma: 0.3
#      patience: 1
#      factor: 0.5
#      min_lr: 0.00001
#      verbose: True
    epochs: 15
    augmentation: mix_transform