path: /mnt/ssd1/datasets/open_ai/
predictions-name: predictions_train_incrnv2-pseudo-exp1.csv
visualize:
  ids: []
prepare-target:
  save: True
make-folds:
  nfolds: 10
  only_verified: True
  verified_in_train: False
inference:
  ids: test_ids.csv
  tta: True
  mode: test
  holdout: 0.05
  verified: True
#  clipping: [0.01, 0.99]
blend:
   predictions: []
evaluation:
  verified_only: True
model:
  folds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  data_params:
    batch_size: 32
    num_workers: 32
    augmentation_params:
      resize: 299
  train_params:
    name: incrnv2-pseudo-exp1
    model: models_zoo.classification.inception.InceptionResNetV2
    model_params:
      pretrained: True
      num_classes: 5
    loss: losses.CrossEntropyLoss
    loss_params: {}
    metrics: [losses.CrossEntropyLoss]
    steps_per_epoch: 10000
    accumulation: 1
  stages:
  -
    load_best: False
    optimizer: Adam
    optimizer_params:
      lr: 0.0003
    scheduler: MultiStepLR
    scheduler_params:
      milestones: [7, 10]
      gamma: 0.3
    epochs: 15
    augmentation: mix_transform
